version: '3.5'

services:
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_USER: sample
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U excellocal -d excellocal
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - ./testdata/schema:/docker-entrypoint-initdb.d
